### Register
POST http://127.0.0.1:8000/api/auth/register
Content-Type: application/json

{
  "name": "Yazid",
  "email": "yazid@gmail.com",
  "password": "yazid123"
}

### Login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
  "email": "yazid@gmail.com",
  "password": "yazid123"
}

### Logout
DELETE http://127.0.0.1:8000/api/auth/logout
Content-Type: application/json
Authorization: Bearer 14|7gmhRB5DtCVDhN2evQcHwxDftQy1v8TsDugI9FGr1f28b7f9

### Get Profile
GET http://127.0.0.1:8000/api/auth/profile
Authorization: Bearer 12|NaGrjHMxZvgiUYMKi4xFX9vX9qG2jpVWGe9Y1Cwxab724167